pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - approved-reviews-by=@fedora-infra/data-team
  - check-success=Checks
  - check-success=Licenses
  - check-success=Documentation
  - check-success=Unit tests (py36)
  - check-success=Unit tests (py37)
  - check-success=Unit tests (py38)
  - check-success=Unit tests (py39)
  name: default