# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: datagrepper.spec
issue_repository: https://github.com/fedora-infra/datagrepper

# add or remove files that should be synced
files_to_sync:
    - datagrepper.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: datagrepper
# downstream (Fedora) RPM package name
downstream_package_name: datagrepper
sync_changelog: true

srpm_build_deps:
  - poetry
  - curl
  - pytest

actions:
    create-archive:
        - "poetry build -f sdist"
        - "sh -c 'echo dist/datagrepper-$(poetry version -s).tar.gz'"
    get-current-version:
        - "poetry version -s"
    post-upstream-clone:
        - "sh -c 'curl -sSL https://install.python-poetry.org | python3 -'"

jobs:
  # upon upstream PRs, perform copr builds and test them
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream release, perform copr builds
  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development
      project: datagrepper

  # upon downstream changes, create a PR upstream with sync'd files from above
  - job: sync_from_downstream
    trigger: commit

  # land upstream release in fedora dist-git - no builds
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create an srpm from upstream and submit a scratch build to koji
  - job: production_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # downstream automation

  # trigger a build in koji for a new dist-git commit
  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create a new update in bodhi for a successful koji build. directly related to `koji_build`
  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development
