# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: datagrepper.spec

# add or remove files that should be synced
files_to_sync:
    - datagrepper.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: datagrepper
# downstream (Fedora) RPM package name
downstream_package_name: datagrepper
sync_changelog: true

srpm_build_deps:
  - poetry
  - wget
  - pytest

actions:
   create-archive:
        - "poetry build -f sdist"
        - "sh -c 'echo dist/datagrepper-$(poetry version -s).tar.gz'"
   get-current-version:
        - "poetry version -s"
   post-upstream-clone:
       # we need poetry v1.1.7 because of a bug in 1.1.8 where python evaluates incorrectly
       - "sh -c 'wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py && python3 install-poetry.py --version 1.1.7'"
       - "rm install-poetry.py"
   fix-spec-file: []

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # Testing-farm temporatily off until issue solved:
  # https://gitlab.com/testing-farm/general/-/issues/44
  #  - job: tests
  #  trigger: pull_request
  #  metadata:
  #    targets:
  #      - fedora-latest-stable
  #      - fedora-development

  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development
      project: datagrepper

  - job: sync_from_downstream
    trigger: commit

  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  - job: production_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development
